## 🌐 Scraping de Coordenadas desde Google Maps

En esta sección se utiliza **Selenium** para automatizar búsquedas en [Google Maps](https://www.google.com/maps) con el objetivo de obtener coordenadas geográficas (latitud y longitud) para direcciones incompletas o faltantes en el dataset original.

Este proceso es útil para **completar valores nulos** en campos como `latitud` y `longitud`, cuando la dirección del predio sí está disponible.

---

### ⚙️ Lógica del scraping:

1. Se itera sobre todas las **direcciones únicas** del dataset (`direccion_completa`).
2. Para cada dirección:
   - Se accede a la página de Google Maps.
   - Se escribe la dirección en el cuadro de búsqueda (`Melbourne` se añade para precisión geográfica).
   - Se espera a que cargue el mapa.
3. Se captura la **URL actual** del navegador, que contiene las coordenadas.
4. Se usa una expresión regular para extraer los valores de `latitud` (`x`) y `longitud` (`y`).
5. En caso de error (dirección inválida, fallo de carga, etc.):
   - Se guarda el registro con valores vacíos para revisión posterior.
6. Se construye una lista de diccionarios con las coordenadas extraídas.

---

> ⚠️ **Importante:** Este enfoque depende del comportamiento de la interfaz web de Google Maps, por lo que es sensible a cambios en el DOM. También se debe tener en cuenta el respeto a los términos de uso de Google.

In [1]:
import sys
import os
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)
from config import *
import pandas as pd
pd.options.display.max_columns = None
import numpy as np

from sqlalchemy import create_engine

engine_pg = create_engine('postgresql://intro:data123@localhost:5433/bdintrods')

with open(os.path.join(SCRIPTS_QUERIES_DIR, 'direcciones.sql'), 'r', encoding='utf-8') as file:
        query = file.read()
#query = "SELECT * FROM tabla_estudiantes WHERE edad >= 20"

df = pd.read_sql(query, con=engine_pg)
df.head()

,suburbio,direccion,habitaciones,tipo,agente_inmobiliario,distancia_centro_km,codigo_postal,banios,aparcamientos,m2,m2_construidos,consejo_gob_area,x,y,region,nro_prop_en_suburbio,fec_venta,anio_construccion,metodo,target,direccion_completa,dir,ubicacion
0,Port Melbourne,1001/101 Bay St,2,u,Barry,3.5,3207,NaN,NaN,NaN,NaN,Melbourne City Council,None,None,Southern Metropolitan,8648.0,201711,None,vendida_prev_no_divulgada,NaN,"Port Melbourne, 1001/101 Bay St, 3207",1,0
1,St Kilda,1002/6 St Kilda Rd,1,u,hockingstuart,6.1,3182,NaN,NaN,NaN,NaN,Port Phillip City Council,None,None,Southern Metropolitan,13240.0,201608,None,prop_vendida_prev,440000.0,"St Kilda, 1002/6 St Kilda Rd, 3182",1,0
2,Southbank,1003/133 City Rd,1,u,Inner,1.2,3006,NaN,NaN,NaN,NaN,Melbourne City Council,None,None,Southern Metropolitan,8400.0,201602,None,vendida_prev_no_divulgada,NaN,"Southbank, 1003/133 City Rd, 3006",1,0
3,Melbourne,1007/594 St Kilda Rd,2,u,Gary,2.8,3000,NaN,NaN,NaN,NaN,Melbourne City Council,None,None,Northern Metropolitan,17496.0,201607,None,prop_vendida,607000.0,"Melbourne, 1007/594 St Kilda Rd, 3000",1,0
4,Abbotsford,1009/1 Acacia Pl,2,u,Jellis,3.0,3067,NaN,NaN,NaN,NaN,Yarra City Council,None,None,Northern Metropolitan,4019.0,201801,None,puja_del_vendedor,750000.0,"Abbotsford, 1009/1 Acacia Pl, 3067",1,0

In [2]:
# IMPORTAR LIBRERÍAS
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import re
import time

In [30]:
df_otro = pd.read_csv(os.path.join(DATA_EXTERNAL_DIR, 'ubicaciones.csv'))
df_otro.shape

(7827, 3)

In [29]:
df_otro[-df_otro.x.isnull()].to_csv(os.path.join(DATA_EXTERNAL_DIR, 'ubicaciones.csv'), index = False)

In [21]:
df_ = df[~df['direccion_completa'].isin(df_otro['direccion_completa'].unique())]

In [23]:
df_.direccion_completa.unique()

array(['Northcote, 101/231 St Georges St, 3070',
       'South Yarra, 101/40 Chapel Mw, 3141',
       'Greenvale, 102 Venezia Prm, 3059',
       'Chelsea, 10 Dennington La, 3196',
       'Kurunjang, 10 Gunsynd Mw, 3337', 'Epping, 10 Minerva Ri, 3076',
       'Plumpton, 10 Pinnacle Wy, 3335',
       'Wantirna South, 11/61 Cathies La, 3152',
       'Point Cook, 1/17 Park Av, 3030',
       'South Morang, 11A Raphael Ri, 3752',
       'Wyndham Vale, 11 Hoddle Lk, 3024',
       'Rowville, 11 Kilcatten Ri, 3178',
       'Keilor East, 11 Mainridge Vs, 3033',
       'South Yarra, 1/2 Chapel Mw, 3141',
       'Brunswick East, 12 Dianella Wky, 3057',
       'MacLeod, 12 Hester Wk, 3085', 'Balwyn, 12 Kaleno Vw, 3103',
       'Deer Park, 12 Melissa Nk, 3023',
       'Croydon North, 13 Ambon Ri, 3136',
       'Werribee, 13 Oradala Ri, 3030', 'Epping, 13 Raven Wk, 3076',
       'Craigieburn, 13 Tusmore Ri, 3064',
       'Maribyrnong, 13 Vista Ri, 3032',
       'Craigieburn, 14 Clopton Ri, 3064',
       'Prahran, 14 Ellesmere La, 3181', 'Richmond, 14 McCrae Mw, 3121',
       'Craigieburn, 14 Viewrise Wk, 3064',
       'Craigieburn, 15 Brecon Nk, 3064',
       'Kensington, 15 Cakebread Mw, 3031',
       'Brunswick East, 15 Elsie Mw, 3057',
       'Craigieburn, 15 Millstream Ps, 3064',
       'Templestowe Lower, 15 Ranleigh Ri, 3107',
       'Kensington, 15 Taylor Mw, 3031',
       'Doncaster, 1/62 Rathmullen Qd, 3108',
       'South Morang, 16 Avion Ri, 3752', 'Bulleen, 16 Chateau Ri, 3105',
       'Mernda, 16 Erindale Ri, 3754',
       'Williamstown, 16 Oconnell Mw, 3016',
       'Essendon, 176A Olgadi St, 3040', 'Doreen, 17 Belmont Ri, 3754',
       'Templestowe Lower, 17 Chatsworth Qd, 3107',
       'Brunswick East, 17 Lomandra Wky, 3057',
       'Maribyrnong, 17 Ribbony Wk, 3032',
       'Bundoora, 1/8 Barlow Ri, 3083', 'Delahey, 18 Bluestone Wk, 3037',
       'Caroline Springs, 18 Etheridge Ri, 3023',
       'Balwyn, 18 Kaleno Vw, 3103', 'Keilor East, 18 Mainridge Vs, 3033',
       'Templestowe Lower, 18 Ranleigh Ri, 3107',
       'Brunswick, 18 Rope Wk, 3056',
       'Point Cook, 198 Saltwater Prm, 3030',
       'Sydenham, 19 Boberrit Wyn, 3037',
       'Clyde North, 19 Fleuve Ri, 3978',
       'Blackburn South, 19 Illowra Wk, 3130',
       'Mernda, 19 Stradling Ri, 3754', 'Warrandyte, 1 Homewood Ri, 3113',
       'South Morang, 1 Kakadu Vw, 3752',
       'Bundoora, 1 Springwood Vw, 3083',
       'Docklands, 2007/2 Newquay Prm, 3008',
       'South Yarra, 201/5 Chapel Mw, 3141',
       'Hawthorn, 209/8 Luton La, 3122',
       'Craigieburn, 20 Marchmont Ri, 3064',
       'Epping, 2/24 Redding Ri, 3076', 'Mernda, 22 Henwood Ri, 3754',
       'Craigieburn, 22 Marchmont Ri, 3064',
       'Preston, 2/30 Ovando St, 3072', 'Yallambie, 23 Cascades Vw, 3085',
       'Mernda, 23 Stradling Ri, 3754',
       'Doncaster, 2/42 Windella Qd, 3108',
       'South Yarra, 24 Chapel Mw, 3141', 'Mernda, 24 Stradling Ri, 3754',
       'Rowville, 25 Tetragona Qd, 3178',
       'North Melbourne, 25 Wilson Mw, 3051',
       'Craigieburn, 26 Grange Ri, 3064',
       'Point Cook, 288 Saltwater Prm, 3030',
       'Port Melbourne, 2 Beacon Vs, 3207',
       'Aspendale, 2 Harrison La, 3195', 'Plenty, 2 Hawk Vw, 3090',
       'Port Melbourne, 2 Lagoon La, 3207', 'Croydon, 2 Oakwood Ri, 3136',
       'Maribyrnong, 301/20 Pier La, 3032',
       'Richmond, 304/1 Studio Wk, 3121',
       'Maribyrnong, 307/20 Pier La, 3032',
       'Templestowe Lower, 30 Chatsworth Qd, 3107',
       'Bundoora, 30 Zenith Ri, 3083', 'Malvern, 3/101 9 Somers Av, 3144',
       'Doncaster East, 31 Buvelot Wyn, 3109',
       'Coburg North, 31 Camera Wk, 3058',
       'Pakenham, 32 Waterford Ri, 3810', 'Sunbury, 33 Miller St, 3429',
       'Epping, 3/3 Redding Ri, 3076', 'Keilor East, 34 West Gwy, 3033',
       'Port Melbourne, 36 Beacon Vs, 3207',
       'Mill Park, 36 Peugeot Prst, 3082',
       'Doncaster, 36 Rathmullen Qd, 3108',
       'Sunbury, 36 Stewarts La, 3429',
       'Kensington, 37 Cakebread Mw, 3031',
       'Sydenham, 38a Bungarim Wyn, 3037',
       'Bentleigh East, 38 Lahona Av, 3165',
       'Roxburgh Park, 3/9 Polesden Mw, 3064',
       'Mill Park, 3 Bradham Dr, 3082', 'Sunshine West, 3 Brent Mw, 3020',
       'Kew, 3 Holly Dr, 3101', 'Brunswick East, 3 Lomandra Wky, 3057',
       'Berwick, 3 Lords Ri, 3806', 'Craigieburn, 3 Riverway Vw, 3064',
       'Templestowe, 3 Robhill Ri, 3106',
       'South Yarra, 402/1 Chapel Mw, 3141',
       'Docklands, 406/30 Newquay Prm, 3008',
       'Templestowe Lower, 42 Chatsworth Qd, 3107',
       'Taylors Hill, 42 Hardware La, 3037',
       'Coburg North, 43 Camera Wk, 3058',
       'Craigieburn, 43 Riverway Vw, 3064',
       'Wattle Glen, 47 Neerim Ri, 3096',
       'Meadow Heights, 4a Rocklands Ri, 3048',
       'Port Melbourne, 4 Beacon Vs, 3207',
       'Cheltenham, 4 Charnwood La, 3192', 'Bulleen, 4 Chateau Ri, 3105',
       'Craigieburn, 4 Cropton Ri, 3064',
       'South Morang, 4 Kipping Ri, 3752', 'Eltham, 4 Lyons Ri, 3095',
       'Bundoora, 4 Magdalen Mw, 3083',
       'South Morang, 4 Rialton Ri, 3752', 'Beaumaris, 4 Ruxton Ri, 3193',
       'Doncaster, 4 Scenic Ri, 3108', 'Bundoora, 4 Winterhill Lk, 3083',
       'Docklands, 505/2 Newquay Prm, 3008',
       'Melbourne, 5/27 Flinders La, 3000',
       'Templestowe Lower, 55 Chatsworth Qd, 3107',
       'Mernda, 58 Basilica Vs, 3754',
       'Port Melbourne, 59 Beacon Vs, 3207',
       'Craigieburn, 5 Brayford Nk, 3064',
       'Glen Iris, 5 Brixton Ri, 3146',
       'Doncaster East, 5 Buvelot Wyn, 3109',
       'Templestowe, 5 Caminole Wyn, 3106',
       'Taylors Lakes, 5 Chlotte Ct, 3038',
       'Brunswick East, 5 Dianella Wky, 3057',
       'Williamstown, 5 Dover La, 3016', 'Templestowe, 5 Dunloe Ri, 3106',
       'Epping, 5 Granite Out, 3076', 'Footscray, 5 Hartman Wk, 3011',
       'Mill Park, 5 Olsen Wk, 3082', 'Craigieburn, 5 Riverway Vw, 3064',
       'South Yarra, 602/3 Chapel Mw, 3141',
       'Melbourne, 608/547 Flinders La, 3000',
       'Craigieburn, 69 Parkside Ri, 3064',
       'Port Melbourne, 6 Beacon Vs, 3207',
       'Aspendale Gardens, 6 Hilda Mw, 3195',
       'Collingwood, 6 Mansard La, 3066',
       'Wyndham Vale, 6 Narmara Mw, 3024',
       'Maribyrnong, 6 Vista Ri, 3032',
       'Coburg North, 72 Camera Wk, 3058', 'Brunswick, 7 Rope Wk, 3056',
       'Ferntree Gully, 7 Salina Ri, 3156',
       'North Warrandyte, 7 Sloans Rd, 3113',
       'Frankston South, 7 Tangenong Ri, 3199',
       'Avondale Heights, 7 Thackeray Qd, 3034',
       'Craigieburn, 7 Tusmore Ri, 3064',
       'Lysterfield, 89 Oaktree Ri, 3156',
       'Templestowe Lower, 8 Chatsworth Qd, 3107',
       'Balwyn North, 8 Colby St, 3104',
       'Templestowe, 8 Cottswold Ri, 3106',
       'Templestowe Lower, 8 Eagle Ri, 3107',
       'Templestowe, 8 Emerald Ri, 3106',
       'Greensborough, 8 Omaru Ri, 3088',
       'Doncaster, 8 Rathmullen Qd, 3108',
       'Templestowe, 9 Emerald Ri, 3106',
       'Doncaster East, 9 Harkaway Ri, 3109',
       'Roxburgh Park, 9 Marsden Wk, 3064', 'Coburg, 9 Parklane Mw, 3058',
       'Keilor East, 9 West Gwy, 3033', 'Niddrie, 9 Willow Cr, 3042',
       'MacLeod, 9 Woodlands Ri, 3085'], dtype=object)

In [24]:
df_.shape

(173, 23)

In [25]:
# CONFIGURACIÓN DEL DRIVER
options = webdriver.ChromeOptions()
# options.add_argument('--incognito') # modo incógnito
options.add_argument('--start-maximized')
options.add_argument('--disable-notifications')
options.add_argument('--no-sandbox')
options.add_argument('--verbose')
prefs = {"profile.default_content_setting_values.notifications" : 2}

options.add_experimental_option("prefs",prefs)

driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()),
                            options = options)

In [26]:
list_data = list()
for dir in df_.sample(df_.shape[0]).direccion_completa.unique():
    dict_data = dict()
    try:
        url = 'https://www.google.com/maps'
        driver.get(url)
        time.sleep(0.25)
        search_input_xpath = "//label[contains(text(), 'Buscar en Google Maps')]/parent::div[1]/following-sibling::input"
        search_input = driver.find_element(By.XPATH, search_input_xpath)

        search_input.clear()
        search_input.send_keys(dir + ', Melbourne')
        search_input.send_keys(Keys.ENTER)
        time.sleep(4)

        url = str(driver.current_url)
        regex_geo = re.compile(r'(.+)!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)')
        time.sleep(1)
        dict_data['direccion_completa'] = dir 
        dict_data['x'] = regex_geo.match(url).group(2)
        dict_data['y'] = regex_geo.match(url).group(3)

        list_data.append(dict_data)
    except:
        dict_data = dict()
        dict_data['direccion_completa'] = dir 
        dict_data['x'] = ''
        dict_data['y'] = ''
        list_data.append(dict_data)

In [316]:
# ## Guardamos los datos:
# import csv
# fuente = 'ubicaciones.csv'
# path_fname = os.path.join(DATA_EXTERNAL_DIR, fuente)
# with open(path_fname, 'w', newline = '') as f:
#     writer =csv.DictWriter(
#         f,
#         delimiter = ',',
#         quotechar = '"',
#         fieldnames = list_data[0].keys()
#     )
#     writer.writeheader()
#     writer.writerows(list_data)

In [27]:
## añadimos datos:
import csv
fuente = 'ubicaciones.csv'
path_fname = os.path.join(DATA_EXTERNAL_DIR, fuente)
with open(path_fname, 'a', newline = '') as f:
    writer =csv.DictWriter(
        f,
        delimiter = ',',
        quotechar = '"',
        fieldnames = list_data[0].keys()
    )
    writer.writerows(list_data)

In [34]:
df_otro

                           direccion_completa          x           y
0       Port Melbourne, 1001/101 Bay St, 3207 -37.840625  144.939556
1          St Kilda, 1002/6 St Kilda Rd, 3182 -37.856620  144.983440
2           Southbank, 1003/133 City Rd, 3006 -37.823361  144.963506
3       Melbourne, 1007/594 St Kilda Rd, 3000 -37.849605  144.979908
4          Abbotsford, 1009/1 Acacia Pl, 3067 -37.811406  145.013802
...                                       ...        ...         ...
7822            Mentone, 2/5 Palermo St, 3194 -37.990315  145.066355
7823       Glen Iris, 8/64 Edgar St Nth, 3146 -37.850025  145.046550
7824  Altona North, 2/324 Blackshaws Rd, 3025 -37.831376  144.853502
7825       Taylors Hill, 30 Hardware La, 3037 -37.696212  144.771357
7826            Brunswick, 3 Latrobe St, 3056 -37.761343  144.971332

[7827 rows x 3 columns]

In [35]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

engine = create_engine('postgresql://intro:data123@localhost:5433/bdintrods')
df_otro.to_sql('ubicaciones_scraping', con=engine, index=False, if_exists='replace', chunksize=1000, method='multi')
print("✅ Tabla creada exitosamente en PostgreSQL.")

✅ Tabla creada exitosamente en PostgreSQL.